# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-23 06:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Ime')),
            ],
        ),
        migrations.CreateModel(
            name='GeoPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lon', models.FloatField(default=0.0, verbose_name='GEO dolžina')),
                ('lat', models.FloatField(default=0.0, verbose_name='GEO širina')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='areas.Area', verbose_name='Območje')),
            ],
        ),
    ]
