# Generated by Django 2.0.5 on 2018-12-24 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='geopoint',
            name='timestamp',
            field=models.PositiveIntegerField(default=0, verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(db_index=True, max_length=32, verbose_name='Ime'),
        ),
    ]
