# Generated by Django 2.0.5 on 2018-12-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0002_auto_20181224_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geopoint',
            name='timestamp',
            field=models.PositiveIntegerField(default=0, unique=True, verbose_name='Timestamp'),
        ),
    ]
